services:
  web:
    image: devt101/basic:latest
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    environment:
      # If your container PHP entrypoint reads this, it can toggle error display
      PHP_DISPLAY_ERRORS: "1"
    restart: unless-stopped
  # Add this to your compose.yml under services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
